from elasticsearch import Elasticsearch
from dotenv import load_dotenv

load_dotenv()
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.getenv("elastic_password")

# Found in the 'Manage Deployment' page
CLOUD_ID = os.get_env("cloud_id")
# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)
