from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "p5iqqHyCAebVnHYOrkWqhJNi"

# Found in the 'Manage Deployment' page
CLOUD_ID = "Search_engine:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvJDg1ODQ1MWEzYTQwMTQwMzI5ODVlMjRiNDVkYjdhYmVmJGVhZjRhYjczMWE5NzQ4MTZiZGMxYmZkYmE0NDU3MDdj"

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)